{
 "title": "My Validator",
 "time": { "from": "2020-06-12T14:42:37.488Z", "to": "2020-06-12T18:06:46.489Z" },
 "panels": [
  {
   "title": "BlazeNet Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Blocks Expected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_epoch_block_expected_number"
    }
   ]
  },
  {
   "title": "% Online",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(near_epoch_block_produced_number / near_epoch_block_expected_number ) * 100"
    }
   ]
  },
  {
   "title": "% Stake vs Seat Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(near_current_stake / near_seat_price) * 100"
    }
   ]
  },
  {
   "title": "Node Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "peer_connections_total" }
   ]
  },
  {
   "title": "Peer Blocks Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(BLOCK_RECEIVED_TOTAL[5m])" }
   ]
  },
  {
   "title": "Blocks Produced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_epoch_block_produced_number"
    }
   ]
  },
  { "title": "NEAR Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "near_block_number" }
   ]
  },
  {
   "title": "Blocks Speed (3m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(near_block_number[3m]) * 100\n"
    }
   ]
  },
  {
   "title": "Seat Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "near_seat_price" },
    {}
   ]
  },
  {
   "title": "Validators Online",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_active_total" }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes[10m])))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( 1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])"
    }
   ]
  }
 ]
}