{
 "title": "My Validator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "BlazeNet Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks Expected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_epoch_block_expected_number{instance=\"blazenet.io\", job=\"near\"}"
    }
   ]
  },
  {
   "title": "Current Stake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "near_current_stake{instance=\"blazenet.io\", job=\"near\"}"
    }
   ]
  },
  {
   "title": "% Online",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(near_epoch_block_produced_number{instance=\"blazenet.io\", job=\"near\"} / near_epoch_block_expected_number{instance=\"blazenet.io\", job=\"near\"} ) * 100"
    }
   ]
  },
  {
   "title": "% Stake vs Seat Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(near_current_stake{instance=\"blazenet.io\", job=\"near\"} / near_seat_price{instance=\"blazenet.io\", job=\"near\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "peer_connections_total{instance=\"blazenet.io\",job=\"validator\"}"
    }
   ]
  },
  {
   "title": "Peer Blocks Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(BLOCK_RECEIVED_TOTAL{instance=\"blazenet.io\",job=\"validator\"}[5m])"
    }
   ]
  },
  {
   "title": "Blocks Produced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_epoch_block_produced_number{instance=\"blazenet.io\", job=\"near\"}"
    }
   ]
  },
  {
   "title": "Seat Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_seat_price{instance=\"blazenet.io\", job=\"near\"}"
    },
    {}
   ]
  },
  { "title": "NEAR Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Blocks Speed (3m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(near_block_number{instance=\"blazenet.io\", job=\"near\"}[3m]) * 100\n"
    }
   ]
  },
  {
   "title": "EPOCH Start Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_epoch_start_height{instance=\"blazenet.io\", job=\"near\"}"
    }
   ]
  },
  {
   "title": "Validators Online",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_active_total{instance=\"blazenet.io\",job=\"validator\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_block_number{instance=\"blazenet.io\", job=\"near\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"blazenet.io\",job=\"node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=\"blazenet.io\",job=\"node\"}[10m]) + avg_over_time(node_memory_Cached_bytes{instance=\"blazenet.io\",job=\"node\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{instance=\"blazenet.io\",job=\"node\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{instance=\"blazenet.io\",job=\"node\"}[10m])))"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( 1 - node_filesystem_avail_bytes{instance=\"blazenet.io\",job=\"node\"} / node_filesystem_size_bytes{instance=\"blazenet.io\",job=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"blazenet.io\",job=\"node\"}[1m])"
    }
   ]
  }
 ]
}